## Recommender Systems: ##
*Recommendation systems have a significant impact by personalizing content, increasing engagement, and driving revenue in e-commerce and entertainment. They aid users in discovering relevant items, reduce information overload, and enhance decision-making. Targeted marketing and data-driven insights benefit businesses, while fostering long-term customer relationships. These systems facilitate social interaction and community building in online platforms. However, ethical considerations must be prioritized to maintain user trust and privacy in the data-driven landscape. Overall, recommendation systems optimize user experiences and boost platform efficiency, playing a crucial role in shaping the digital world's success and connectivity.
The project involves developing a popularity based recommender system which will display top 50 books along with a Collaborative filtering based Book recommendation system*

In [ ]:
#Importing Necessary Libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [43]:
#Reading the Files
books=pd.read_csv("Books.csv")
Users=pd.read_csv("Users.csv")
Ratings=pd.read_csv("Ratings.csv")

C:\Users\acer\AppData\Local\Temp\ipykernel_6024\256012022.py:1: DtypeWarning: Columns (3) have mixed types. Specify dtype option on import or set low_memory=False.
  books=pd.read_csv("Books.csv")

# Popularity Based Recommender System

In [44]:
#Looking at the Legths of the files
print(len(Ratings))
print(len(Users))
print(len(books))

1149780
278858
271360

In [12]:
#Checking the files for any sort of duplicated values
print(books.duplicated().sum())
print(Ratings.duplicated().sum())
print(Users.duplicated().sum())

0

In [45]:
#Visualisation
Users

        User-ID                            Location   Age
0             1                  nyc, new york, usa   NaN
1             2           stockton, california, usa  18.0
2             3     moscow, yukon territory, russia   NaN
3             4           porto, v.n.gaia, portugal  17.0
4             5  farnborough, hants, united kingdom   NaN
...         ...                                 ...   ...
278853   278854               portland, oregon, usa   NaN
278854   278855  tacoma, washington, united kingdom  50.0
278855   278856           brampton, ontario, canada   NaN
278856   278857           knoxville, tennessee, usa   NaN
278857   278858                dublin, n/a, ireland   NaN

[278858 rows x 3 columns]

In [46]:
#Merging the Ratings and books file 
ratings_name=Ratings.merge(books,on="ISBN")

In [48]:
#Selecting only the Book_Title and the rating counts
num_rating=ratings_name.groupby("Book-Title").count()["Book-Rating"].reset_index()
num_rating.rename(columns={"Book-Rating":"No_Of-Ratings"},inplace=True)
num_rating

                                               Book-Title  No_Of-Ratings
0        A Light in the Storm: The Civil War Diary of ...              4
1                                   Always Have Popsicles              1
2                    Apple Magic (The Collector's series)              1
3        Ask Lily (Young Women of Faith: Lily Series, ...              1
4        Beyond IBM: Leadership Marketing and Finance ...              1
...                                                   ...            ...
241066                                      Ã?Â?lpiraten.              2
241067                     Ã?Â?rger mit Produkt X. Roman.              4
241068                                Ã?Â?sterlich leben.              1
241069                              Ã?Â?stlich der Berge.              3
241070                                  Ã?Â?thique en toc              2

[241071 rows x 2 columns]

In [49]:
#Calculations of the average _ratings
avg_rat=ratings_name.groupby("Book-Title").mean()["Book-Rating"].reset_index()
avg_rat.rename(columns={"Book-Rating":"Average_Ratings"},inplace=True)
avg_rat

                                               Book-Title  Average_Ratings
0        A Light in the Storm: The Civil War Diary of ...         2.250000
1                                   Always Have Popsicles         0.000000
2                    Apple Magic (The Collector's series)         0.000000
3        Ask Lily (Young Women of Faith: Lily Series, ...         8.000000
4        Beyond IBM: Leadership Marketing and Finance ...         0.000000
...                                                   ...              ...
241066                                      Ã?Â?lpiraten.         0.000000
241067                     Ã?Â?rger mit Produkt X. Roman.         5.250000
241068                                Ã?Â?sterlich leben.         7.000000
241069                              Ã?Â?stlich der Berge.         2.666667
241070                                  Ã?Â?thique en toc         4.000000

[241071 rows x 2 columns]

In [59]:
#Merging the count and average ratings dataframes on book title
ui_mat=num_rating.merge(avg_rat,on="Book-Title")
new_mat=ui_mat[ui_mat["No_Of-Ratings"]>=250].sort_values("Average_Ratings",ascending=False)
popular_df=new_mat.head(50)

In [67]:
#Formation of popular dataframe by merging the above with books file
popular_df=popular_df.merge(books,on="Book-Title").drop_duplicates("Book-Title")[["Book-Title","No_Of-Ratings","Average_Ratings","Image-URL-M","Year-Of-Publication","Book-Author"]]

In [73]:
#Saving the File
# popular_df.to_csv("Popular_books.csv",index=False)

# Collaborative Based Recommender System

In [78]:
#Selecting the users who have rated more than 200 movies
x=ratings_name.groupby("User-ID").count()["Book-Rating"]>200
frequent_raters=x[x].index
filtered_ratings=ratings_name[ratings_name["User-ID"].isin(frequent_raters)]
filtered_ratings

,User-ID,ISBN,Book-Rating,Book-Title,Book-Author,Year-Of-Publication,Publisher,Image-URL-S,Image-URL-M,Image-URL-L
2,6543,034545104X,0,Flesh Tones: A Novel,M. J. Rose,2002,Ballantine Books,http://images.amazon.com/images/P/034545104X.0...,http://images.amazon.com/images/P/034545104X.0...,http://images.amazon.com/images/P/034545104X.0...
5,23768,034545104X,0,Flesh Tones: A Novel,M. J. Rose,2002,Ballantine Books,http://images.amazon.com/images/P/034545104X.0...,http://images.amazon.com/images/P/034545104X.0...,http://images.amazon.com/images/P/034545104X.0...
7,28523,034545104X,0,Flesh Tones: A Novel,M. J. Rose,2002,Ballantine Books,http://images.amazon.com/images/P/034545104X.0...,http://images.amazon.com/images/P/034545104X.0...,http://images.amazon.com/images/P/034545104X.0...
15,77940,034545104X,0,Flesh Tones: A Novel,M. J. Rose,2002,Ballantine Books,http://images.amazon.com/images/P/034545104X.0...,http://images.amazon.com/images/P/034545104X.0...,http://images.amazon.com/images/P/034545104X.0...
16,81977,034545104X,0,Flesh Tones: A Novel,M. J. Rose,2002,Ballantine Books,http://images.amazon.com/images/P/034545104X.0...,http://images.amazon.com/images/P/034545104X.0...,http://images.amazon.com/images/P/034545104X.0...
...,...,...,...,...,...,...,...,...,...,...
1030883,275970,1880837927,0,The Theology of the Hammer,Millard Fuller,1994,Smyth &amp; Helwys Publishing,http://images.amazon.com/images/P/1880837927.0...,http://images.amazon.com/images/P/1880837927.0...,http://images.amazon.com/images/P/1880837927.0...
1030884,275970,188717897X,0,The Ordeal of Integration: Progress and Resent...,Orlando Patterson,1998,Civitas Book Publisher,http://images.amazon.com/images/P/188717897X.0...,http://images.amazon.com/images/P/188717897X.0...,http://images.amazon.com/images/P/188717897X.0...
1030885,275970,1888889047,0,Pushcart's Complete Rotten Reviews &amp; Rejec...,Bill Henderson,1998,Pushcart Press,http://images.amazon.com/images/P/1888889047.0...,http://images.amazon.com/images/P/1888889047.0...,http://images.amazon.com/images/P/1888889047.0...
1030886,275970,1931868123,0,There's a Porcupine in My Outhouse: Misadventu...,Mike Tougias,2002,Capital Books (VA),http://images.amazon.com/images/P/1931868123.0...,http://images.amazon.com/images/P/1931868123.0...,http://images.amazon.com/images/P/1931868123.0...
1030887,275970,3411086211,10,Die Biene.,Sybil GrÃ?Â¤fin SchÃ?Â¶nfeldt,1993,"Bibliographisches Institut, Mannheim",http://images.amazon.com/images/P/3411086211.0...,http://images.amazon.com/images/P/3411086211.0...,http://images.amazon.com/images/P/3411086211.0...

In [80]:
#Selecting the movie which have been rated atleast 50 ratings
y=filtered_ratings.groupby("Book-Title").count()['Book-Rating']>=50
famous_books=y[y].index
final_ratings=filtered_ratings[filtered_ratings["Book-Title"].isin(famous_books)]

In [81]:
final_ratings

,User-ID,ISBN,Book-Rating,Book-Title,Book-Author,Year-Of-Publication,Publisher,Image-URL-S,Image-URL-M,Image-URL-L
63,278418,0446520802,0,The Notebook,Nicholas Sparks,1996,Warner Books,http://images.amazon.com/images/P/0446520802.0...,http://images.amazon.com/images/P/0446520802.0...,http://images.amazon.com/images/P/0446520802.0...
65,3363,0446520802,0,The Notebook,Nicholas Sparks,1996,Warner Books,http://images.amazon.com/images/P/0446520802.0...,http://images.amazon.com/images/P/0446520802.0...,http://images.amazon.com/images/P/0446520802.0...
66,7158,0446520802,10,The Notebook,Nicholas Sparks,1996,Warner Books,http://images.amazon.com/images/P/0446520802.0...,http://images.amazon.com/images/P/0446520802.0...,http://images.amazon.com/images/P/0446520802.0...
69,11676,0446520802,10,The Notebook,Nicholas Sparks,1996,Warner Books,http://images.amazon.com/images/P/0446520802.0...,http://images.amazon.com/images/P/0446520802.0...,http://images.amazon.com/images/P/0446520802.0...
74,23768,0446520802,6,The Notebook,Nicholas Sparks,1996,Warner Books,http://images.amazon.com/images/P/0446520802.0...,http://images.amazon.com/images/P/0446520802.0...,http://images.amazon.com/images/P/0446520802.0...
...,...,...,...,...,...,...,...,...,...,...
1026724,266865,0531001725,10,The Catcher in the Rye,Jerome David Salinger,1973,Scholastic Library Pub,http://images.amazon.com/images/P/0531001725.0...,http://images.amazon.com/images/P/0531001725.0...,http://images.amazon.com/images/P/0531001725.0...
1027923,269566,0670809381,0,Echoes,Maeve Binchy,1986,Penguin USA,http://images.amazon.com/images/P/0670809381.0...,http://images.amazon.com/images/P/0670809381.0...,http://images.amazon.com/images/P/0670809381.0...
1028777,271284,0440910927,0,The Rainmaker,John Grisham,1995,Island,http://images.amazon.com/images/P/0440910927.0...,http://images.amazon.com/images/P/0440910927.0...,http://images.amazon.com/images/P/0440910927.0...
1029070,271705,B0001PIOX4,0,Fahrenheit 451,Ray Bradbury,1993,Simon &amp; Schuster,http://images.amazon.com/images/P/B0001PIOX4.0...,http://images.amazon.com/images/P/B0001PIOX4.0...,http://images.amazon.com/images/P/B0001PIOX4.0...
1030868,275970,1586210661,9,Me Talk Pretty One Day,David Sedaris,2001,Time Warner Audio Major,http://images.amazon.com/images/P/1586210661.0...,http://images.amazon.com/images/P/1586210661.0...,http://images.amazon.com/images/P/1586210661.0...

In [86]:
#FORMATION OF USER INTERACTION MATRIX
UI_MAT=final_ratings.pivot_table(index="Book-Title",columns="User-ID",values="Book-Rating")
UI_MAT

User-ID,254,2276,2766,2977,3363,4017,4385,6251,6323,6543,...,271705,273979,274004,274061,274301,274308,275970,277427,277639,278418
Book-Title,,,,,,,,,,,,,,,,,,,,,
1984,9.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,10.0,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN
1st to Die: A Novel,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,9.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2nd Chance,NaN,10.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,...,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,0.0,NaN
4 Blondes,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
A Bend in the Road,0.0,NaN,7.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Year of Wonders,NaN,NaN,NaN,7.0,NaN,NaN,NaN,NaN,NaN,0.0,...,NaN,9.0,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN
You Belong To Me,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Zen and the Art of Motorcycle Maintenance: An Inquiry into Values,NaN,NaN,NaN,NaN,0.0,NaN,NaN,0.0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN
Zoya,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
"\O\"" Is for Outlaw""",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,8.0,NaN,NaN,NaN,NaN,NaN

In [92]:
#Filling the Nan values with 0 
UI_MAT.fillna(0,inplace=True)

In [93]:
#Distance metric used are cosine similarity
from sklearn.metrics.pairwise import cosine_similarity

In [106]:
#Similarity scores with one movie with the other movies
similarity_scores=cosine_similarity(UI_MAT)
similarity_scores.shape

(706, 706)

In [111]:
#Defining the Recommendation system
def recommend(book_name):
    #fetching Index
    index=np.where(UI_MAT.index==book_name)[0][0]
    similar_items=sorted(list(enumerate(similarity_scores[index])),key=lambda x:x[1],reverse=True)[1:6]
    for i in similar_items:
        print(UI_MAT.index[i[0]])

In [108]:
# sorted(list(enumerate(similarity_scores[0])),key=lambda x:x[1],reverse=True)[1:6]

[(47, 0.2702651417103732),
 (545, 0.26396193711234966),
 (82, 0.2366937434740099),
 (634, 0.23299389358170397),
 (551, 0.2262639743141286)]

In [115]:
#Testing
recommend("Midnight")

Winter Moon
Dark Rivers of the Heart
Shadowfires
While My Pretty One Sleeps
Before I Say Good-Bye